project_id = "vlysgwxcvcwmwcafvwyv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://vlysgwxcvcwmwcafvwyv.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 1025
pop3_port = 1110

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[edge_functions]
enabled = true

[functions.auth-signup]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-verify]
verify_jwt = false

[functions.auth-logout]
verify_jwt = false

[functions.supervisor-manage-students]
verify_jwt = false