// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlysgwxcvcwmwcafvwyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZseXNnd3hjdmN3bXdjYWZ2d3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTA1MDksImV4cCI6MjA2NTk2NjUwOX0.Q-s6HXawVTmcpgGyktbDW-KY0T30jPNWylVIXX4xC-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);